service: myTestService
provider:
  name: aws
  runtime: provided.al2023
  region: eu-central-1
  architecture: x86_64
package:
  individually: true
  patterns:
    - bootstrap
functions:
  hello:
    handler: bootstrap
